#!/usr/bin/env bash
# Regenerate ops/requirements-prod.lock: the exact runtime dependency set a
# prod release's venv is built from (no dev or memory extras). Prod venvs are
# keyed by this file's hash, so an unchanged lock means a deploy reuses the
# existing venv and installs nothing (daydream/prodctl.py).
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
python3 -m venv "$TMP/venv"
"$TMP/venv/bin/pip" install -q --upgrade pip
# Constrain to the dev venv's exact versions: prod must run what the test
# suite ran against, not whatever resolves freshest today.
"$ROOT/.venv/bin/pip" freeze --exclude-editable | grep -v '^daydream' > "$TMP/constraints.txt"
# Install from a copy so setuptools' build/ never lands in the repo.
mkdir "$TMP/src"
cp -r "$ROOT/pyproject.toml" "$ROOT/daydream" "$TMP/src/"
"$TMP/venv/bin/pip" install -q -c "$TMP/constraints.txt" "$TMP/src"
{
    echo "# Generated by tools/lock_prod_requirements.sh on $(date -u +%Y-%m-%d). Do not edit by hand."
    echo "# Runtime deps only (pyproject [project].dependencies), pinned to the dev venv's versions."
    "$TMP/venv/bin/pip" freeze --exclude daydream | sort -f
} > "$ROOT/ops/requirements-prod.lock"
echo "wrote ops/requirements-prod.lock ($(grep -vc '^#' "$ROOT/ops/requirements-prod.lock") packages)"
